# Generated by Django 4.0.3 on 2022-04-13 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familiares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('FechaDeNacimiento', models.DateField()),
                ('dni', models.IntegerField()),
                ('edad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_master', models.CharField(max_length=50)),
                ('apellido_master', models.CharField(max_length=50)),
                ('email_master', models.EmailField(max_length=254)),
                ('dni_master', models.IntegerField()),
                ('telefono_master', models.IntegerField()),
                ('profesion_master', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=50)),
                ('apellido_empresa', models.CharField(max_length=50)),
                ('email_empresa', models.EmailField(max_length=254)),
                ('dni_empresa', models.IntegerField()),
                ('telefono_empresa', models.IntegerField()),
                ('profesion_empresa', models.CharField(max_length=25)),
            ],
        ),
    ]
